### ISSUE TITLE
Apply the C Coding Standard on the file.c and file.h

### ISSUE THREAD

**Issue by GiovanniL30** [Arvss07/9472-AppDev-Prelims-C#14]
Task: Kindly create a new branch and apply the C Coding Standard on the file. c and file.h

Follow this coding standard
[9472-C_coding-standard.pdf](https://github.com/user-attachments/files/17993131/9472-C_coding-standard.pdf)

**Comment by Arvss07** [comment]
Kindly check my work on branck `file.c-coding-standard` with the hash id `7a76704`

Please notify me if there are changes that needed to be applied.

Thanks!
